name: PHP Code Check

on:
  push:
    branches:
      - master

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y php
        ls webcode

    - name: PHP lint synops.php
      run: php -l ./webcode/synops.php
      
    - name: PHP lint synopsturm.php
      run: php -l ./webcode/synopsturm.php
      
    - name: PHP lint synopsturm.php
      run: php -l ./webcode/synopsturm.php
      
    - name: PHP lint control.php  
      run: php -l ./webcode/control.php  
      
    - name: PHP lint cors.php
      run: php -l ./webcode/cors.php
      
