name: Spellcheck PHP files

on:
  push: [push, pull_request_target]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install codespell
      run: |
        pip3 install codespell
          
    - name: Run codespell for synops.php
      run: |
        codespell --check-filenames --ignore-words-list="TODO" webcode/synops.php
        
    - name: Run codespell for synopsturm.php
      run: |
        codespell --check-filenames --ignore-words-list="TODO" webcode/synopsturm.php
