name: Spellcheck PHP files

on:
  push:
    branches:
      - master

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
    - name: Install codespell
      run: |
        ls
        pip3 install codespell
          
    - name: Run codespell
      run: |
        codespell --check-filenames --ignore-words-list="TODO" webcode/control.php
